version: "3.3"

services:
  proxy:
    build:
      context: .
    image: proxy.nginx12
    networks:
      - test
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  backend:
    image: php:7.1.6-apache
    networks:
      - test
    ports:
      - "8080:80"

networks:
  test:
