version: "3.3"

services:
  proxy:
    build:
      context: .
    image: proxy.nginx12
    networks:
      - test
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    image: backend
    networks:
      - test
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"

networks:
  test:
