#base image
FROM php:7.1.6-apache

#redis and other
#RUN pecl install redis-3.1.0 \
#    && pecl install xdebug-2.5.0 \
#    && docker-php-ext-enable redis xdebug

#enable rewrite module
RUN a2enmod rewrite
